title: Portfolio
logo: /assets/img/logo.jpg
description: Hello, my name is Ming-Jung YU, I'm a Back End Engineer. This is my portfolio for list all projects, products and side-projects I have done and in progress.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal