title: Portfolio
logo: /assets/img/logo.jpg
description: Hello, I'm Ming, I have worked as Python Back End Engineer for two years. This is my portfolio for list all projects, products and side-projects I joined before and in progress.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal